// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Higher$CreedOopPatterns = require("../src/higher.bs.js");

Higher$CreedOopPatterns.Newtype1({ });

var Eq = Higher$CreedOopPatterns.Newtype2({ });

function refl(param) {
  return {
          eqaux: (function (x) {
              return x;
            })
        };
}

function subst(ab, ctxt) {
  return Curry._1(ab.eqaux, ctxt);
}

function trans(ab, bc) {
  return Curry._1(bc.eqaux, ab);
}

function cast(eq, x) {
  return Curry._1(eq.eqaux, x);
}

function symm(eq) {
  Higher$CreedOopPatterns.Newtype1({ });
  return Curry._1(eq.eqaux, {
              eqaux: (function (x) {
                  return x;
                })
            });
}

var Leibniz = {
  Eq: Eq,
  refl: refl,
  subst: subst,
  trans: trans,
  symm: symm,
  cast: cast
};

exports.Leibniz = Leibniz;
/*  Not a pure module */
