// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function foo(hasMethodBar) {
  return hasMethodBar.bar();
}

console.log(({
          bar: (function () {
              return "works";
            })
        }).bar());

exports.foo = foo;
/*  Not a pure module */
